core/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path

from users.views import (
    login,
    register,
    logout,
    profile,
    unverified_email,
    verify_email,
    password_reset,
    new_password,
    settings
)

app_name = 'users'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('unverified-email/', unverified_email, name='unverified-email'),
    path('verify-email/', verify_email, name='verify-email'),
    path('password-reset/', password_reset, name='password-reset'),
    path('password-reset/<str:token>/', new_password, name='new-password'),
    path('settings/', settings, name='account-settings')
]

core/models.py
from django.db import models


class BaseModel(models.Model):

    created_at = models.DateTimeField('created at', auto_now_add=True)
    updated_at = models.DateTimeField('updated at', auto_now=True)
    deleted_at = models.DateTimeField('deleted at', null=True, blank=True)

    class Meta:
        abstract = True

users/models/profiles.py
from django.db import models
from django.utils import timezone

from users.models import User


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile',
    )
    first_name = models.CharField('first name', max_length=150, blank=True)
    last_name = models.CharField('last name', max_length=150, blank=True)

    def __str__(self):
        return f'@{self.user.username}'

    def save(self, *args, **kwargs):
        self.user.updated_at = timezone.now()
        self.user.save()
        super().save(*args, **kwargs)

users/models/users.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from core.models import BaseModel


class User(AbstractUser, BaseModel):

    username = models.CharField('username', max_length=50, unique=True)
    email = models.EmailField('email address', unique=True)

    # This fields will be in the Profile Model.
    first_name = None
    last_name = None
    date_joined = None

    email_verified_at = models.DateTimeField('email verified at', null=True, blank=True)
    email_verification_token = models.CharField('email verification token', max_length=32, blank=True)

    def __str__(self):
        return f'@{self.username}'

    def get_full_name(self):
        return f'{self.profile.first_name} {self.profile.last_name}'

    def get_short_name(self):
        return self.username

core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

users/views/account_settings.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def settings(request):
    return render(request, 'users/settings.html')

users/views/email.py
import secrets

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages
from django.utils import timezone

from users.decorators import email_unverified_only
from users.utils import send_user_email_verification


@login_required
@email_unverified_only
def unverified_email(request):
    if request.method == 'POST':
        user = request.user
        send_user_email_verification(request, user)
        msg = f'We sent a verification email to {user.email}. Please follow the instructions in it.'
        messages.success(request, msg)
    return render(request, 'users/unverified_email.html')


@login_required
@email_unverified_only
def verify_email(request):
    user = request.user
    token = request.GET.get('token', None)
    user_email_verification_token = user.email_verification_token
    if not token or not secrets.compare_digest(token, user_email_verification_token):
        messages.error(request, 'There was an error verifying your email.')
        return redirect('users:unverified-email')
    user.email_verified_at = timezone.now()
    user.email_verification_token = ''
    user.save()
    messages.info(request, 'Your email was verified.')
    return redirect('users:profile')

users/views/profile.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from users.decorators import email_verification_required


@login_required
@email_verification_required
def profile(request):
    return render(request, 'users/profile.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    {% block scripts %}{% endblock %}
    <title>{% block title %}Auth App - {% endblock %}</title>
</head>
<body class="bg-light">
    <main>
        {% include 'layouts/header.html' %}
        <div class="container mt-4">

            {% if messages %}
                {% for message in messages %}
                    <div class="alert {% if message.level_tag == 'error' %} alert-danger {% else %} alert-{{ message.level_tag }} {% endif %}" role="alert">
                        <span>{{ message.message }}</span>
                    </div>
                {% endfor %}
            {% endif %}

            {% block content %}{% endblock %}
        </div>
        {% include 'layouts/footer.html' %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    {% block bottom_scripts %}{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %} {{ block.super }} Home {% endblock %}

{% block content %}
<div class="text-center">
    <h1>Welcome To Auth App</h1>
    <span class="fst-italic text-muted">This app is for learning the flow of authentication in Django & beyond.</span>
    <p class="mt-4">Get started:</p>
    <div class="row justify-content-center">
        <div class="col-12 col-md-5 col-lg-4">
            {% if user.is_authenticated %}
                <a class="btn btn-dark btn-lg d-block" href="{% url 'users:profile' %}">Visit your profile</a>
            {% else %}
                <a class="btn btn-outline-dark btn-lg d-block" href="{% url 'users:login' %}">Login</a>
                <span class="my-2 d-block">or</span>
                <a class="btn btn-warning btn-lg d-block" href="{% url 'users:register' %}">Create an account</a>
            {% endif %}
            </div>
        </div>
</div>
{% endblock %}

templates/layouts/footer.html
<div class="fixed-bottom py-2 bg-white text-center">
    Made with ❤️ by <a href="https://github.com/juliosinaysantos" target="_blank">@juliosinaysantos</a>
</div>

templates/layouts/header.html
<header class="navbar navbar-light navbar-expand-md bg-white border-bottom sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
            Auth App
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navCollapse"
            aria-controls="navCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <nav class="collapse navbar-collapse" id="navCollapse">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          {{ user.username }}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDarkDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
                            <li><a class="dropdown-item" href="{% url 'users:account-settings' %}">Settings</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    </li>
                    <li class="nav-item ms-md-3 d-grid gap-2">
                        <a class="btn btn-dark" href="#">Register</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

templates/users/login.html
{% extends 'base.html' %}

{% block title %} {{ block.super }} Login {% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-12 col-md-7 col-lg-6 col-xl-4">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title text-center">Sign In</h1>
                <form action="" method="POST" class="mt-5">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}">
                    <div class="mb-3">
                        <label for="login">Username or Email</label>
                        <input
                            class="form-control {% if form.login.errors %}is-invalid{% endif %}"
                            id="login"
                            name="login"
                            type="text"
                            value="{% firstof form.login.value '' %}"
                        >
                        <small class="invalid-feedback">
                            {% if form.login.errors %}{{ form.login.errors.0 }}{% endif %}
                        </small>
                    </div>
                    <div class="mb-3">
                        <label for="password">Enter your password</label>
                        <input
                            class="form-control {% if form.password.errors %}is-invalid{% endif %}"
                            id="password"
                            name="password"
                            type="password"
                        >
                        <small class="invalid-feedback">
                            {% if form.password.errors %}{{ form.password.errors.0 }}{% endif %}
                        </small>
                    </div>
                    <div class="mb-3 form-check">
                        <input type="checkbox" class="form-check-input" name="rememberme" id="rememberme">
                        <label class="form-check-label" for="rememberme">Remember me</label>
                    </div>
                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-warning btn-lg">Login</button>
                    </div>
                    <div class="text-center mt-2">
                        <small>
                            <a href="{% url 'users:password-reset' %}">Forgot your password?</a>
                        </small>
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <small>Do you need an account? <a href="{% url 'users:register' %}">Register</a></small>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/new_password.html
{% extends 'base.html' %}

{% block title %}Change Your Password - Auth App{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-12 col-md-7 col-lg-6 col-xl-4">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title text-center">Change password for @{{ username }}</h1>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="password">Password</label>
                            <input
                                class="form-control {% if form.password.errors %}is-invalid{% endif %}"
                                id="password"
                                name="password"
                                type="password"
                            >
                            <small class="invalid-feedback">
                                {% if form.password.errors %}
                                    {{ form.password.errors.0 }}
                                {% endif %}
                            </small>
                        </div>
                        <div class="mb-3">
                            <label for="password_confirmation">Confirm your password</label>
                            <input
                                class="form-control {% if form.password_confirmation.errors %}is-invalid{% endif %}"
                                id="password_confirmation"
                                name="password_confirmation"
                                type="password"
                            >
                            <small class="invalid-feedback">
                                {% if form.password_confirmation.errors %}
                                    {{ form.password_confirmation.errors.0 }}
                                {% endif %}
                            </small>
                        </div>
                        <div class="d-grip gap-2">
                            <button type="submit" class="btn btn-warning btn-lg">Change password</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}

{% block title %} {{ block.super }} @{{ user.username }} {% endblock %}

{% block content %}
    <h1>Profile {{ user.username }}</h1>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block title %} {{ block.super }} Register {% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-12 col-md-7 col-lg-6 col-xl-4">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title text-center">Sign Up</h1>
                <form action="" method="POST" class="mt-5">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username">Username</label>
                        <input
                            class="form-control  {% if form.username.errors %}is-invalid{% endif %}"
                            name="username"
                            id="username"
                            type="text"
                            value="{% firstof form.username.value '' %}"
                        >
                        <small class="invalid-feedback">
                            {% if form.username.errors %}{{ form.username.errors.0 }}{% endif %}
                        </small>
                    </div>
                    <div class="mb-3">
                        <label for="email">Enter your Email</label>
                        <input
                            class="form-control  {% if form.email.errors %}is-invalid{% endif %}"
                            name="email"
                            id="email"
                            type="text"
                            value="{% firstof form.email.value '' %}"
                        >
                        <small class="invalid-feedback">
                            {% if form.email.errors %}{{ form.email.errors.0 }}{% endif %}
                        </small>
                    </div>
                    <div class="mb-3">
                        <label for="password">Choose your password</label>
                        <input
                            class="form-control {% if form.password.errors %}is-invalid{% endif %}"
                            id="password"
                            name="password"
                            type="password"
                        >
                        <small class="invalid-feedback">
                            {% if form.password.errors %}{{ form.password.errors.0 }}{% endif %}
                        </small>
                    </div>
                    <div class="mb-3">
                        <label for="password">Confirm your password</label>
                        <input
                            class="form-control {% if form.password_confirmation.errors %}is-invalid{% endif %}"
                            id="password_confirmation"
                            name="password_confirmation"
                            type="password"
                        >
                        <small class="invalid-feedback">
                            {% if form.password_confirmation.errors %}{{ form.password_confirmation.errors.0 }}{% endif %}
                        </small>
                    </div>
                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-warning btn-lg">Create account</button>
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <small>Already have an account? <a href="{% url 'users:login' %}">Login</a></small>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/reset_password.html
{% extends 'base.html' %}

{% block title %} Forgot your password? - Auth App{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-12 col-md-7 col-lg-6 col-xl-4">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title text-center">Reset Your Password</h1>
                    <p class="text-muted">Enter your user account's email address and we will send you a password reset link.</p>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input
                                class="form-control {% if form.email.errors %}is-invalid{% endif %}"
                                name="email"
                                placeholder="Enter your email address"
                                type="text"
                                value="{% firstof form.email.value '' %}"
                            >
                            <small class="invalid-feedback">
                                {% if form.email.errors %}{{ form.email.errors.0 }}{% endif %}
                            </small>
                        </div>
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-warning">Send password reset email</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/settings.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ block.super }} Account settings (@{{ user.username }}) {% endblock %}

{% block scripts %}
    <script src="https://unpkg.com/vue@next"></script>
{% endblock %}

{% block content %}
    {% verbatim %}
    <div id="app">
        <h1>{{ page }}</h1>
    </div>
    {% endverbatim %}
{% endblock %}

{% block bottom_scripts %}
<script src="{% static 'settings/js/main.js' %}"></script>
{% endblock %}

templates/users/unverified_email.html
{% extends 'base.html' %}

{% block title %} Please verify your email address {% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-12 col-md-7 text-center">
            <h1>Please verify your email address</h1>
            <p class="text-muted">Before you can see your profile page, we need you to verify your email address.</p>
            <p class="text-muted">An email containing verification instructions was sent to <span class="fw-bold">{{ user.email }}</span>.</p>
            <div class="row justify-content-center">
                <div class="col-12 col-lg-5 mt-3">
                    <div class="d-grid gap-2">
                        <form action="{% url 'users:unverified-email' %}" method="POST" class="d-grid gap-2">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-dark">Resend email verification</button>
                        </form>
                    </div>
                </div>
                <div class="col-12 col-lg-5 mt-3">
                    <div class="d-grid gap-2">
                        <a href="#" class="btn btn-outline-dark">Change your email</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}